# Generated by Django 4.1.2 on 2022-11-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familia',
            new_name='MiFamilia',
        ),
    ]
